# -*- coding: utf-8 -*-
"""Exercise.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WQEsv3aO9bTaH2kBaO2nA6TAdvx1EBsV
"""

import numpy as np

import pandas as pd

print(np.version)

A = np.zeros((2,3))
print(A)

from io import StringIO

import requests

csv_path = "https://github.com/HamoyeHQ/HDSC-Introduction-to-Python-for-machine-learning/files/7768140/FoodBalanceSheets_E_Africa_NOFLAG.csv"
s=requests.get(csv_path).text
data = pd.read_csv(StringIO(s))

data.head()

A = data.groupby("Item")
A.head()

A["Y2015"].mean()
A["Y2015"].std()

data.corr()

data.std(axis=0, skipna=True)

data.isnull().sum()

g = data.groupby("Element")
g.head()

data["Area"].count()